### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by jakoch** [jakoch/ttauri#1]
**ttauri uses vcpkg to pull dependencies**

- [ ] use vcpkg to pull and install the majority of external dependencies using vcpkg
  - only two 3th-party dependencies do not have a vcpkg package (= do not have a vcpkg port):
     - tz - https://github.com/eggert/tz
     - renderdoc - that's single file include         
  - [x] create manifest `vcpkg.json`
  - [x] remove external dependencies from git, which are available via vcpkg
  - [x] project-local dependency installation and linking (`ttauri/vcpkg_installed/x64-windows-static`)
  - [x] global dependency installation and linking (`vcpkg_root/installed/x64-windows-static`)
  - [x] triplets (target architecture - platform - linkage type)
     - [ ] x64-windows
     ```
      set(VCPKG_TARGET_ARCHITECTURE x64)
      set(VCPKG_CRT_LINKAGE dynamic)
      set(VCPKG_LIBRARY_LINKAGE dynamic)
      ```` 
     - [x] x64-windows-static
     ```
      set(VCPKG_TARGET_ARCHITECTURE x64)
      set(VCPKG_CRT_LINKAGE static)
      set(VCPKG_LIBRARY_LINKAGE static)
      ```` 
     - [ ] x64-windows-md?
      ```
      set(VCPKG_TARGET_ARCHITECTURE x64)
      set(VCPKG_CRT_LINKAGE dynamic)
      set(VCPKG_LIBRARY_LINKAGE static)
      ```` 
  
```
{
      "name": "ttauri",
      "version-string": "0.1.0",
      "license": "BSL-1.0",
      "homepage": "https://github.com/ttauri-project/ttauri",
      "description": "A portable, low latency, retained-mode GUI library written in C++.",
      "dependencies": [
        "fmt",
        "date",
        "gtest",
        "vulkan",
        "vulkan-memory-allocator"
      ]
}
```

-----

**user-project uses vcpkg to pull dependencies, including ttauri**

- [ ] create vcpkg port for ttauri itself
    This will enable the users of ttauri (who are creating their own application) to pull and build it automatically via vcpkg.
   - [ ] create port file
      - https://github.com/microsoft/vcpkg/blob/master/docs/about/faq.md#can-i-contribute-a-new-library
      - https://github.com/Microsoft/vcpkg/blob/master/CONTRIBUTING.md
   - [ ] test install via port file
   - [ ] contribute it to "microsoft/vcpkg" repo
      - [ ] *BLOCKER*: they build the ports. ttauri requires 16.9 Preview.
   - when port PR landed, use `vcpkg.json` of user project and pull ttauri via vcpkg
    ```
    {
      "name": "my-calculator",
      "version-string": "0.1.0",
      "license": "MIT",
      "description": "A calculator app using ttauri.",
      "dependencies": [
        "ttauri",
        "catch2"
      ]
    }
   ```

-----

**Build automation**

- [ ] requirements
  - [x] MSVC / VC2019 Preview
  - [x] Vulkan_SDK
  - [x] Vulkan Runtime (for vulkan-1.dll) on dynamic builds
  - [x] CMake 3.19 (.4)
  - [x] curl for downloading
  - [ ] RenderDoc ? for renderdoc.dll?
     - use default install locations as defined here: https://github.com/ttauri-project/ttauri/blob/5e679398159ab65c06c259c973202d41cf7f4a54/src/ttauri/GUI/RenderDoc.cpp#L19-L23
     - https://renderdoc.org/stable/1.12/RenderDoc_1.12_64.zip
  - [ ] release artifacts
     - lib + deps(sdk) + headers
     - ttauri_demo + lib + res
  - discuss: `release file name`, `library name` and `folder layout`?
  - library name, the normal prefix is `lib` on Linux, the normal suffix is `.lib` on Windows
     - `libttauri.so` on Linux and `ttauri.lib` on Windows
     - [CMAKE_STATIC_LIBRARY_PREFIX](https://cmake.org/cmake/help/latest/variable/CMAKE_STATIC_LIBRARY_PREFIX.html) 
     - [CMAKE_STATIC_LIBRARY_SUFFIX](https://cmake.org/cmake/help/latest/variable/CMAKE_STATIC_LIBRARY_SUFFIX.html)  
     - if UNIX -> `set_target_properties(ttauri PROPERTIES DEBUG_POSTFIX "d")`
   
**Github Actions | Workflows**
- [x] create `.github/workflow/build.yml`
- [ ] Blocker: they only provide VS2019 Enterprise
   - [ ] update to VS2019 Preview

**Appveyor**
- [x] provides image ` Visual Studio 2019 Preview`
   - see https://www.appveyor.com/docs/windows-images-software/#visual-studio-2019
      - this page says it's 16.9 Preview 4
      - source says it's 16.9 Preview 2, https://ci.appveyor.com/project/jakoch/ttauri/builds/37896014/job/p6i7k2eles6giwb6#L187
      - well 👍🏼  
- [x] curl, see https://www.appveyor.com/docs/windows-images-software/#tools
- [x] create `appveyor.yml`
- [x] caching of vcpkg build packages and vulkan_sdk
- [x] prepare sections for tests, artifacts 
- [x] prepare artifacts uploading to github releases
- [x] prepare build matrix 
   - [x] msvc2019 (Status: builds)
   - [x] clang (Status: doesn't build, because old external/googletest)
- [x] fix double install of vcpkg packages
   -  do not run `vpkg install` before `vcpkg integrate`.. the other way around it's messed up.
   -  do not run `vcpkg install` on cli, additionally to letting the cmake vcpkg toolchain integration handle the installation
     - this will use two install location, the global one and the app/project-local one which is undesired
   - [x] solved: install vcpkg -> integrate with triplet -> let cmake vcpkg toolchain integration handle the installation
- [x] add `local` install for the build targets  + resources
    -  [ ] ttauri library
       - [x] lib
       - [ ] include headers
       - [ ] any other resources "/share"
          - [ ] docs, copyright
 - [x] discuss adoption of `include(GNUInstallDirs)` to have standardized folder names
 - [ ] vcpkg libraries are not installed, when x64-windows (dll's)
    - is there an automatic way of copying these libraries?
    - X_VCPKG_APPLOCAL_DEPS_INSTALL?
    - `https://github.com/microsoft/vcpkg/issues/1653#issuecomment-767069079`
- [x] add versioning scheme using `VERSION`
    -  changed to a `git describe --tag` approach... 
    -  read version data from `src/ttauri/version.hpp` for now. scheme is `[version]-[current commit]`
    
----

**Build Targets + Installation**
- [ ] Case 1: ttarui is built as a subproject
  - ttauri is checked in as third-party lib and used with `add_subdirectory(external/ttauri)`
  - [ ] Q: do we need to introduce a master_project flag to signal that?
     - it's a master project, when `CMAKE_CURRENT_SOURCE_DIR` = `CMAKE_CURRENT_SOURCE`  
- [ ] Case 2: ttauri is build and installed locally
- [ ] Case 3: ttauri is build and installed using vcpkg
------

**IDE Integrations**

**Visual Studio 2019**

- `CMakeSettings.json`

**Visual Studio Code**

- `.vscode\settings.json`:

```
{
    "C_Cpp.vcpkg.enabled": false,
    "cmake.configureSettings": {

        // support the "vcpkg" branch
        //"VCPKG_TARGET_TRIPLET": "x64-windows-static",
        //"CMAKE_TOOLCHAIN_FILE": "${env:VCPKG_ROOT}scripts/buildsystems/vcpkg.cmake",

        // support the main branch (non-vpkg)
        "BUILD_TZ_LIB": "ON",
        "USE_SYSTEM_TZ_DB": "ON",
        "ENABLE_DATE_TESTING": "OFF"
    }
}
```

------

**Issues**
  - [x] FindVulkan() doesnt find "glslc.exe", see https://github.com/Kitware/CMake/blob/master/Modules/FindVulkan.cmake
     - how is this possible? https://github.com/Kitware/CMake/blob/master/Modules/FindVulkan.cmake#L68
     - Solved by fixing AddShader.cmake to use vulkan::glslc target executable
  - [x] build error: C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\oaidl.h(487,17)
     - same errors as described in https://developercommunity.visualstudio.com/content/problem/1187741/unexpected-warnings-from-system-headers-with-1680.html
     - also https://stackoverflow.com/questions/65402366/c5105-and-other-compiler-warnings-when-building-with-github-actions-winsdk-10
     - Solved by specifying CMAKE_SYSTEM_VERSION 10.0 before project
  - [x] GTest errors
     - issue is either "linkage" or "upstream is newer"
        - upstream is newer ! and has bugs - `https://github.com/google/googletest/issues/2881`
     - non build blocking
     - [x] solved by reverting to old `external/googletest`
         - after reading all the github issues over in the googletest repo.. ooof. 👎🏼
         - https://github.com/google/googletest/issues/1017 XML output of google_text.xml has no junit formatter/writer
         - [x] cxx11 and last release v1.10.0 from October 2019. please consider migrating to catch !
  - [x] replicating Visual Studio behavior from the command line
      - transfer settings from CMakeSettings.json to CLI
      - the majority of settings are build options for "external/date"
      - removed all after testing, if they are used somewhere:
```
  Manually-specified variables were not used by the project:
    BUILD_TZ_LIB
    BUILD_WITH_STATIC_CRT
    ENABLE_DATE_TESTING
    USE_SYSTEM_TZ_DB
    gtest_force_shared_crt
```

  - [x] error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease
     - maybe -DBUILD_WITH_STATIC_CRT:BOOL=OFF - nope
     - solved by https://stackoverflow.com/a/56490614/1163786
       - set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
       - https://cmake.org/cmake/help/latest/prop_tgt/MSVC_RUNTIME_LIBRARY.html
       - https://cmake.org/cmake/help/latest/variable/CMAKE_MSVC_RUNTIME_LIBRARY.html
   - [ ] Blocker: src\ttauri\os_detect.hpp(107,1): fatal error C1189: #error:  "Unknown C++ version" during cmake_pch generation
      - https://github.com/ttauri-project/ttauri/blob/main/src/ttauri/os_detect.hpp#L102-L107
      - _cplusplus is undefined. oooof. 
         - this needs -D_WIN32_WINNT version number? win32_winnt is set now           
         - [using windows headers](https://docs.microsoft.com/de-de/windows/win32/winprog/using-the-windows-headers?redirectedfrom=MSDN)
      - is this syntax valid for msbuild `-Zc:__cplusplus -Zc:preprocessor`?
        - slash maybe? nope. the new syntax is valid. 
        - https://cmake.org/cmake/help/git-stage/command/target_precompile_headers.html
     - how can i set compiler options for the "cmake_pch" generation step?
     - [x] trying to avoid the issue by adding build option TT_BUILD_PCH and disabling PCH generation 
         - this leads to massive amount of headers not found. in other words: baseline build depends on PCH. 
         - would be nice to have progressive refinement: baseline should build with PCH off, Tests off, Optimizations off
         - [x] added TT_BUILD_OPTIMIZE, TT_BUILD_TESTS, TT_BUILD_EXAMPLE
- [x] https://ci.appveyor.com/project/jakoch/ttauri/builds/37874471#L1223
  - gap_buffer.hpp(594,7): warning C4648: standard attribute 'no_unique_address' is ignored 
  - https://developercommunity.visualstudio.com/content/problem/1041135/warning-c4648-standard-attribute-no-unique-address.html
  - disabled warning `/wd4648`
- [x] set clang toolset on cmake 
   - [x] `cmake -T llvm` or  `-T clang-cl`?
      - `-T LLVM` will use upstream LLVM
      - [x] `-T ClangCL`works on 2019 and uses the Microsoft built-in LLVM distribution
- [x] ttauri's `install` target installs googletest, too?
   - disable INSTALL_GTEST
- [ ] MSVC IDE resets automatically to "x64-windows"
    - set "x64-windows-static" in CMakeSettings.json - nope
    - set VCPKG_DEFAULT_TRIPLET - nope
    - set VCPKG_TARGET_TRIPLET - nope
    - set VcpkgTriplet ?
    - is there any other new vcpkg control variable i miss?
- [x] gtest
     -  when we build in static debug mode, errors with GoogleTestAddTests, see https://ci.appveyor.com/project/jakoch/ttauri/builds/37982422/job/ph7qhv75f85emxt7#L1148
     - that's because, when text.exe has an error, it fails ctest and test detection... during build phase
     - Example for gtest and vcpkg: https://github.com/qis/gtest-test
     - https://gitlab.kitware.com/cmake/cmake/-/issues/19518#note_783018 
     - [x] solved by adding: `gtest_discover_tests( DISCOVERY_MODE PRE_TEST)`
--- 
**Notes**

- cl.exe:  [Options a-z](https://docs.microsoft.com/de-de/cpp/build/reference/compiler-options-listed-alphabetically?view=msvc-160) [Options cat](https://docs.microsoft.com/de-de/cpp/build/reference/compiler-options-listed-by-category?view=msvc-160)
- msbuild: [CLI reference](https://docs.microsoft.com/de-de/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2019)
- cmake
  - PUBLIC (for everyone) = INTERFACE (for the other) + PRIVATE (for me)  
  - List CMakeLists.txt 
    - `dir cmakelists.txt /S /B` 
  - check for missing source file includes in folders with target_source directive
    - `dir /B | find /V ".txt"`
- MSVC: [Language Conformance Table](https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance?view=msvc-160&viewFallbackFrom=vs-2019)

**Comment by takev** [comment]
Did you solve the google test problems?
Do you want me to update google test in my repo and fix it?

**Comment by jakoch** [comment]
No, i didn't solve the GTest issues, yet.
I'm not sure, if it is a linkage type problem or due to upstream changes in GTest.
It's also not a real "build blocker", because the build targets "ttauri" and "ttauri_demo" do not depends on GTest.
They would build, but with errors for the test target.
Please don't work on this issue or only if you have enough time for it.

**Comment by jakoch** [comment]
Status Update: https://ci.appveyor.com/project/jakoch/ttauri/builds/37878885
 - MSVC2019 branch is 🟢 🚀
 - Clang branch is 🔴
